# Generated by Django 3.2 on 2021-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_pic',
            field=models.FileField(default=True, upload_to='images/'),
        ),
    ]
