# Generated by Django 3.2 on 2021-06-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_category_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_desc', models.TextField(max_length=300)),
                ('product_pic', models.FileField(upload_to='images/')),
                ('product_price', models.FloatField()),
                ('product_view', models.IntegerField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.category')),
                ('product_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.gender')),
            ],
        ),
    ]
