# Generated by Django 3.2 on 2021-06-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_gender_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_for',
            field=models.CharField(choices=[('Select Gender', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female'), ('Kid', 'Kid'), ('All', 'All')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
