# Generated by Django 3.2 on 2021-06-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20210615_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileusers',
            old_name='gender',
            new_name='user_gender',
        ),
    ]
