# Generated by Django 3.2 on 2021-06-18 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_gender_profileusers_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileusers',
            name='user_gender',
        ),
    ]
