# Generated by Django 3.2 on 2021-07-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_profileusers_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileusers',
            name='city',
            field=models.CharField(default='India', max_length=200),
        ),
        migrations.AddField(
            model_name='profileusers',
            name='doc',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profileusers',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='profileusers',
            name='profile_pic',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
