# Generated by Django 3.2 on 2021-07-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210703_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='mailid',
        ),
    ]
